### ISSUE TITLE
Possible to manually set initial locale?

### ISSUE THREAD

**Issue by eahenke** [JCQuintas/ni18n#166]
First of all, thank you for creating this project! It's working great for me except for one small problem. I'd like to completely decouple initial locale from the Next router, and use a cookie/manually set the locale instead (I am not using domain or subpath internationalized routing).

## The Problem:
In my page's `getServerSideProps`, I call `loadTranslations` with a locale from a cookie. If this locale (in this case, Spanish), does not match the `defaultLocale` from the config (English), then the server will load the Spanish translations, but `appWithi18next` will init i18n with English, causing the client to crash because the English translations weren't loaded. If I include `useSyncLanguage` near my app root it changes the language to Spanish and not crash, but the browser will still fetch the English translations and then re-change the i18n language back to English asynchronously once they are loaded. This causes a flicker of Spanish (desired) -> English content (not desired).

## Potential solution:
In [app-with-i18next.tsx](https://github.com/JCQuintas/ni18n/blob/main/src/app-with-i18next/app-with-i18next.tsx#L36), the initial locale is pulled from Next's `props.router.locale`, which a read-only field set by Next. From what I can tell from reading the Next source code, the only way to consistently force this value to be based on a cookie is with a kind of [hacky redirect from middleware](https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale). I'm wondering if it would be possible to add either an optional check to `props.pageProps.locale` or allow some optional function to set the initial locale? I'd be happy to work on a PR for this feature if you think it's worth adding to this project. Or if maybe there is some existing way to solve this issue with configuration, please let me know. Thank you!

**Comment by JCQuintas** [comment]
Hey, thanks for the feedback, I think this would be a nice addition to the project if you manage to create a PR. I've tried to quickly test some options but didn't succeed.

PR's are always welcome.

**Comment by eahenke** [comment]
@JCQuintas I've got a PR up (https://github.com/JCQuintas/ni18n/pull/168). If you could give it a review when you have a chance that would be great. Looking forward to using this library in production soon, thanks!
