### ISSUE TITLE
loadTranslations does not load the default namespace correctly if not specified in config

### ISSUE THREAD

**Issue by Pryrios** [JCQuintas/ni18n#38]
I have started using ni18n. I had the following ni18nConffig:

```Javascript
import type { Ni18nOptions } from 'ni18n'

export const ni18nConfig: Ni18nOptions = {
  supportedLngs: ['en', 'es'],
  ns: ['layout-default','specific-page'],
}
```

I understood that the first item is the default namespace and always gets loaded, and maybe this is were I was wrong.

In fact it worked ok until I used loadTranslations on getServerSideProps to load the specific-page namespace for a specific page. It loaded _specific-page_ correctly, but not _default-layout_. 

My getServerSideProps:

```Javascript
export const getServerSideProps = async (props) => {
  return {
    props: {
      ...(await loadTranslations(ni18nConfig, props.locale, ['specific-page'])),
    },
  }
}
```

I have solved it by including the defaultNS entry in ni18nConfig:

```Javascript
import type { Ni18nOptions } from 'ni18n'

export const ni18nConfig: Ni18nOptions = {
  supportedLngs: ['en', 'es'],
  ns: ['layout-default','specific-page'],
  defaultNS: 'layout-default'
}
```

Now it works correctly. _default-layout_ gets loaded on every page and _specific-page_ only on specific page. 

Also question: when I use loadTranslations, is the default namespace loaded on server side rendering? I'm assuming it does, but I'm not sure as the default behavior is to load client-side.

**Comment by JCQuintas** [comment]
Hi @Pryrios , some behaviour have changed in the last major version of `i18next` and I'm yet to take a proper look at it to know if any further changes to the documentation are necessary. But glad to hear you were able to solve your problem. :)

The `loadTranslations` function should make the `defaultNS` available as props to the server side renderer. If you check the network tab you will see that some `.json` payloads are loaded with the page, these json should have all the namespaces used when rendering on the server. 

Let me know if you encounter any issue. 👍

**Comment by Pryrios** [comment]
Nothing else for now, thank you for your input and for your module!
